shopping/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>',views.cart_remove, name= 'cart_remove'),
    path('full_remove/<int:product_id>',views.full_remove, name= 'full_remove'),
]

shopping/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('',views.SearchResult, name='SearchResult'),
]

shopping/shopapp/urls.py
from django.urls import path
from . import views


app_name = 'shopapp'
urlpatterns = [
    path('',views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail, name='prodCatdetail'),
]

shopping/shopping/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shopapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping/cart/models.py
from django.db import models
from shopapp.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']
        
    def __str__(self):
        return '{}'.format(self.cart_id)
    
class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return '{}'.format(self.product)
    

shopping/search_app/models.py
from django.db import models

# Create your models here.

shopping/shopapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering =('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shopapp:product_by_category',args=[self.slug])
    
    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now_add= True)
    updated = models.DateField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shopapp:prodCatdetail',args=[self.category.slug, self.slug])
    
    def __str__(self):
        return '{}'.format(self.name)

shopping/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shopapp.models import Product
from .models import CartItem,Cart
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(req):
    cart = req.session.session_key
    if not cart:
        cart = req.session.create()
    return cart

def add_cart(req,product_id):
    product = Product.objects.get(id= product_id)
    try:
        cart = Cart.objects.get(cart_id = _cart_id(req))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(req))
        cart.save(),
    
    try:
        cart_item = CartItem.objects.get(product = product,cart= cart )
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
            
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(req,total = 0,counter = 0,cart_items = None):
    try:
        cart = Cart.objects.get(cart_id = _cart_id(req))
        cart_items = CartItem.objects.filter(cart = cart, active = True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(req,"cart.html",dict(cart_items= cart_items,total= total,counter= counter))

def cart_remove(req,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(req))
    product = get_object_or_404(Product, id= product_id)
    cart_item = CartItem.objects.get(cart = cart, product= product)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(req,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(req))
    product = get_object_or_404(Product, id= product_id)
    cart_item = CartItem.objects.get(cart = cart, product= product)
    cart_item.delete()
    return redirect('cart:cart_detail')

shopping/search_app/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q

# Create your views here.

def SearchResult(req):
    products = None
    query = None
    if 'q' in req.GET:
        query = req.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains = query) | Q(description__contains = query ))
        return render(req,"search.html",{'query':query,'products':products})

shopping/shopapp/views.py
from django.shortcuts import get_object_or_404, render,HttpResponse
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def allProdCat(req,c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug= c_slug)
        products_list = Product.objects.all().filter(category= c_page,available = True)
    else :
        products_list = Product.objects.all().filter(available = True)
    paginator = Paginator(products_list,6)
    try:
        page = int(req.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(req,"category.html",{'category': c_page, 'products': products})

def proDetail(req,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug = c_slug, slug = product_slug)
    except Exception as e:
        raise e
    return render(req,'product.html',{'product': product })

shopping/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/4060fb10bc.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">  
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>  
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</body>
</html>

shopping/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the cart page. proceed to review your items and place the order  
{% endblock %}
{% block title %}
Cart -ABC Company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
    <div class="">
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Your Shopping Cart</h1><br>
            <p class="text-center">
                Please Click <a href="{% url 'shopapp:allProdCat' %}">Here</a> To Continue Shopping
            </p>
        </div>
    </div>
{% else %}
    <div class="">
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">our Shopping Cart</h1>
            <br>
        </div>
        <div class="row mx_auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">Your items</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" width="100px" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-left">
                                    {{cart_item.product.name}}
                                    <br>
                                    SKU : {{cart_item.product.id}}
                                    <br>
                                    Price : ${{cart_item.product.price}}
                                    <br>
                                    Qty : {{cart_item.quantity}} x $ {{cart_item}} 
                                </td>
                                <td>
                                    $ {{cart_item.sub_total}}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %}
                                
                                <td>
                                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                                        <i class="fa fa-plus custom_icon"></i>
                                    </a>&nbsp;
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                                        <i class="fa fa-minus custom_icon"></i>
                                    </a>&nbsp;
                                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                                        <i class="fa fa-trash custom_icon"></i>
                                    </a>
                                </td>
                                {% else %}
                                <td>
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                                        <i class="fa fa-minus custom_icon"></i>
                                    </a>&nbsp;
                                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                                        <i class="fa fa-trash custom_icon"></i>
                                    </a>
                                </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>Checkout</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your Shopping cart items before proceedibg with the order payment.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your Total is: <strong>${{ total }}</strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mx_auto">
                    <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
                </div>
            </div>
        </div>
{% endif %}
    </div>
    
{% endblock %}

shopping/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        welcome to ABC store where you can buy items
    {% endif %} 
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} --ABC store
    {% else %}
        See our collections
    {% endif %} 
{% endblock %}
{% block content %}
    {% if category %}
        <div class="">
            <div class="row my_row_class">
                <div class="mx_auto">
                    <p><a href="{% url 'shopapp:allProdCat' %}">Our Product Collections</a></p>
                </div>
            </div>
        </div>
    {% endif %}
    {% if category %}
        <div class="mx_auto">
                <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
        </div><br>
        <div class="">
            <h1 class="text-center my_title">{{category.name}}</h1>
            <p class="text-justify">{{category.description}}</p>
        </div>
    {% else %}
        <div class="">
            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Our Products" width="1250px;">
        </div><br>
        <div class="">
            <h1 class="text-center my_title">Our Products Collections</h1>
            <p class="text-justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis quisquam doloremque tempora accusantium incidunt! Veniam aspernatur repudiandae dolores qui omnis dolor, ratione explicabo reprehenderit, voluptatibus exercitationem tenetur libero, placeat numquam!</p>
        </div>
    {% endif %}
    <div class="container">
        <div class="row mx_auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width: 18rem;">
                        <a href="{{product.get_url}}"><img  class="img-responsive card-img-top my_image img-fluid"  src="{{product.image.url}}" alt="{{product.name}}"></a>
                        <div class="card-body">
                            <h4>{{product.name}}</h4>
                            <p>{{product.price}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number %} active {% endif %}" >{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>

{% endblock %}
    

shopping/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; ABC tect pvt ltd.All rights Reserved</p>
</div>

shopping/templates/header.html
{% load static %}
<header>
    <!-- <a href="/admin">admin</a> -->
    <center>
        <a href="{% url 'shopapp:allProdCat' %}">
            <img src="{% static 'img/E-Shop.jpg' %}" alt="logo" width="130px">
         </a>
    </center>
</header>

shopping/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Shop
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">All Product</a></li>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping">{{item_count}}</i></a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" role="search" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
      </div>
    </div>
</nav>

shopping/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %} 
        {{ product.description|truncatewords:155 }} 
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} --ABC store
    
    {% endif %} 
{% endblock %}
{% block content %}

<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p>
            <a href="{% url 'shopapp:allProdCat' %}">Home</a> 
            | <a href="{{product.category.get_url}}">{{product.category}}</a> 
            | {{product.name}}
        </p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div class="" style="min-width: 18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width: 452px;">
        </div>
    </div>
    
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div class="">
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Derscription</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
        </div>
    </div>
    
</div>
{% endblock %}

shopping/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    we have verity of products 
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div class="">
    <p class="text-center my_search_text">You have searched for:<b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{product.get_url}}"><img class="card_img_top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
                <div class="row mx_auto">
                    <p class="text-center my_search_text">0 results found</p>
                </div>
        {% endfor %}
    </div>
</div>
{% endblock %}